/**
 * Shared types and interfaces between API and Web applications
 * This package provides type safety across the full stack
 */

/**
 * Standard API response wrapper for all endpoints
 */
export interface ApiResponse<T = any> {
  success: boolean
  data: T
  error: string | null
  timestamp: number
}

/**
 * Ticker data structure (cryptocurrency market data)
 */
export interface Ticker {
  symbol: string                    // Trading pair symbol (e.g., BTC/USDT)
  exchange: string                  // Exchange identifier
  type: 'spot' | 'perp'            // Market type
  bid: number | null                // Highest bid price
  ask: number | null                // Lowest ask price
  last: number | null               // Last traded price
  high24h: number | null            // 24h highest price
  low24h: number | null             // 24h lowest price
  volume24h: number | null          // 24h base volume
  quoteVolume24h: number | null    // 24h quote volume
  change24h: number | null          // 24h absolute change
  percentage24h: number | null      // 24h percentage change
  timestamp: number                 // Data timestamp
  fundingRate?: number | null       // Perpetual funding rate (perp only)
  openInterest?: number | null      // Perpetual open interest (perp only)
}

/**
 * Market information structure
 */
export interface Market {
  id: string                        // Market identifier
  symbol: string                    // Trading pair symbol
  base: string                      // Base currency
  quote: string                     // Quote currency
  type: 'spot' | 'perp'            // Market type
  active: boolean                   // Is market active
  exchange: string                  // Exchange identifier
}

/**
 * Exchange capabilities information
 */
export interface ExchangeInfo {
  name: string                      // Display name
  id: string                        // Exchange identifier
  supported: boolean                // Is supported
  hasSpot: boolean                  // Has spot markets
  hasPerp: boolean                  // Has perpetual markets
}

/**
 * Supported exchanges
 */
export type SupportedExchange = 'binance' | 'bybit' | 'okx'

/**
 * Pagination metadata
 */
export interface PaginationMeta {
  page: number          // Current page number (1-indexed)
  limit: number         // Items per page
  total: number         // Total number of items
  totalPages: number    // Total number of pages
  hasNext: boolean      // Has next page
  hasPrev: boolean      // Has previous page
}

/**
 * Tickers response from /tickers/:exchange
 */
export interface TickersResponse {
  exchange: string
  tickers: Ticker[]
  count: number
  pagination?: PaginationMeta  // Optional pagination metadata
  filters?: {                   // Applied filters
    type?: 'spot' | 'perp'
    search?: string
    sortBy?: string
    sortOrder?: 'asc' | 'desc'
  }
}

/**
 * Markets response from /markets/:exchange
 */
export interface MarketsResponse {
  exchange: string
  markets: Market[]
  count: number
  pagination?: PaginationMeta  // Optional pagination metadata
  filters?: {                   // Applied filters
    type?: 'spot' | 'perp'
    search?: string
    active?: boolean
  }
}

/**
 * Health check response
 */
export interface HealthResponse {
  status: string
  api: string
  database: string
  exchanges: string[]
  timestamp: number
}

/**
 * OHLCV candlestick data (Open, High, Low, Close, Volume)
 * Standard format for chart data across all timeframes
 */
export interface OHLCV {
  timestamp: number     // Candle start timestamp in milliseconds
  open: number          // Opening price
  high: number          // Highest price in the period
  low: number           // Lowest price in the period
  close: number         // Closing price
  volume: number        // Trading volume in base currency
}

/**
 * Supported timeframes for OHLCV data
 * Maps to standard exchange timeframe formats
 */
export type Timeframe = '1m' | '5m' | '15m' | '1h' | '4h' | '1d' | '3d' | '1w'

/**
 * OHLCV response from /ohlcv/:exchange/:symbol
 */
export interface OHLCVResponse {
  exchange: string        // Exchange identifier
  symbol: string          // Trading pair symbol
  timeframe: Timeframe    // Requested timeframe
  candles: OHLCV[]       // Array of candlestick data
  count: number          // Number of candles returned
}

/**
 * Custom pair response from /custom-pair/:exchange/:symbol1/:symbol2
 * Generated by dividing two ticker prices (symbol1 / symbol2)
 */
export interface CustomPairResponse {
  exchange: string           // Exchange identifier
  symbol1: string            // Numerator symbol (e.g., BTC-USDT)
  symbol2: string            // Denominator symbol (e.g., AVAX-USDT)
  customPairSymbol: string   // Resulting pair (e.g., BTC/AVAX)
  timeframe: Timeframe       // Requested timeframe
  marketType: 'spot' | 'perp' // Market type
  candles: OHLCV[]          // Array of custom pair candlestick data
  count: number             // Number of candles returned
}
