/**
 * Shared types and interfaces between API and Web applications
 * This package provides type safety across the full stack
 */

/**
 * Standard API response wrapper for all endpoints
 */
export interface ApiResponse<T = any> {
  success: boolean;
  data: T;
  error: string | null;
  timestamp: number;
}

/**
 * Ticker data structure (cryptocurrency market data)
 *
 * Symbol Notation:
 * - Spot markets: BTC-USDT, SOL-USDT (hyphen separator)
 * - Perpetual markets: BTCUSDT.P, SOLUSDT.P (.P suffix)
 */
export interface Ticker {
  symbol: string; // Trading pair symbol (e.g., BTC-USDT for spot, BTCUSDT.P for perp)
  exchange: string; // Exchange identifier
  type: 'spot' | 'perp'; // Market type
  bid: number | null; // Highest bid price
  ask: number | null; // Lowest ask price
  last: number | null; // Last traded price
  high24h: number | null; // 24h highest price
  low24h: number | null; // 24h lowest price
  volume24h: number | null; // 24h base volume
  quoteVolume24h: number | null; // 24h quote volume
  change24h: number | null; // 24h absolute change
  percentage24h: number | null; // 24h percentage change
  timestamp: number; // Data timestamp
  fundingRate?: number | null; // Perpetual funding rate (perp only)
  openInterest?: number | null; // Perpetual open interest (perp only)
}

/**
 * Market information structure
 *
 * Symbol Notation:
 * - Spot markets: BTC-USDT, SOL-USDT (hyphen separator)
 * - Perpetual markets: BTCUSDT.P, SOLUSDT.P (.P suffix)
 */
export interface Market {
  id: string; // Market identifier
  symbol: string; // Trading pair symbol (e.g., BTC-USDT for spot, BTCUSDT.P for perp)
  base: string; // Base currency
  quote: string; // Quote currency
  type: 'spot' | 'perp'; // Market type
  active: boolean; // Is market active
  exchange: string; // Exchange identifier
}

/**
 * Exchange capabilities information
 */
export interface ExchangeInfo {
  name: string; // Display name
  id: string; // Exchange identifier
  supported: boolean; // Is supported
  hasSpot: boolean; // Has spot markets
  hasPerp: boolean; // Has perpetual markets
}

/**
 * Supported exchanges
 * - binance: Binance (spot + perpetual)
 * - bybit: Bybit (spot + perpetual)
 * - okx: OKX (spot + perpetual)
 * - hyperliquid: Hyperliquid DEX (perpetual only)
 * - upbit: Upbit Korea (spot only)
 */
export type SupportedExchange = 'binance' | 'bybit' | 'okx' | 'hyperliquid' | 'upbit';

/**
 * Pagination metadata
 */
export interface PaginationMeta {
  page: number; // Current page number (1-indexed)
  limit: number; // Items per page
  total: number; // Total number of items
  totalPages: number; // Total number of pages
  hasNext: boolean; // Has next page
  hasPrev: boolean; // Has previous page
}

/**
 * Tickers response from /tickers/:exchange
 */
export interface TickersResponse {
  exchange: string;
  tickers: Ticker[];
  count: number;
  pagination?: PaginationMeta; // Optional pagination metadata
  filters?: {
    // Applied filters
    type?: 'spot' | 'perp';
    search?: string;
    sortBy?: string;
    sortOrder?: 'asc' | 'desc';
  };
}

/**
 * Markets response from /markets/:exchange
 */
export interface MarketsResponse {
  exchange: string;
  markets: Market[];
  count: number;
  pagination?: PaginationMeta; // Optional pagination metadata
  filters?: {
    // Applied filters
    type?: 'spot' | 'perp';
    search?: string;
    active?: boolean;
  };
}

/**
 * Health check response
 */
export interface HealthResponse {
  status: string;
  api: string;
  database: string;
  exchanges: string[];
  timestamp: number;
}

/**
 * OHLCV candlestick data (Open, High, Low, Close, Volume)
 * Standard format for chart data across all timeframes
 */
export interface OHLCV {
  timestamp: number; // Candle start timestamp in milliseconds
  open: number; // Opening price
  high: number; // Highest price in the period
  low: number; // Lowest price in the period
  close: number; // Closing price
  volume: number; // Trading volume in base currency
}

/**
 * Supported timeframes for OHLCV data
 * Maps to standard exchange timeframe formats
 */
export type Timeframe = '1m' | '5m' | '15m' | '1h' | '4h' | '1d' | '3d' | '1w';

/**
 * OHLCV response from /ohlcv/:exchange/:symbol
 *
 * Symbol uses standardized notation:
 * - Spot: BTC-USDT
 * - Perpetual: BTCUSDT.P
 */
export interface OHLCVResponse {
  exchange: string; // Exchange identifier
  symbol: string; // Trading pair symbol (BTC-USDT or BTCUSDT.P)
  timeframe: Timeframe; // Requested timeframe
  candles: OHLCV[]; // Array of candlestick data
  count: number; // Number of candles returned
}

/**
 * Custom pair response from /custom-pair/:exchange/:symbol1/:symbol2
 * Generated by dividing two ticker prices (symbol1 / symbol2)
 */
export interface CustomPairResponse {
  exchange: string; // Exchange identifier
  symbol1: string; // Numerator symbol (e.g., BTC-USDT)
  symbol2: string; // Denominator symbol (e.g., AVAX-USDT)
  customPairSymbol: string; // Resulting pair (e.g., BTC/AVAX)
  timeframe: Timeframe; // Requested timeframe
  marketType: 'spot' | 'perp'; // Market type
  candles: OHLCV[]; // Array of custom pair candlestick data
  count: number; // Number of candles returned
}

/**
 * Asset weight configuration for custom index
 * Each asset has a symbol and its weight in the index (as percentage)
 */
export interface IndexAsset {
  symbol: string; // Asset symbol (e.g., BTC-USDT)
  weight: number; // Weight percentage (0-100)
}

/**
 * Custom index performance data point
 * Shows the index value at a specific timestamp
 */
export interface IndexPerformancePoint {
  timestamp: number; // Timestamp in milliseconds
  value: number; // Normalized index value (starts at 100)
  change: number; // Percentage change from start
}

/**
 * Comparison benchmark data
 * Performance data for USDT/BTC/ETH/SOL benchmarks
 */
export interface BenchmarkPerformance {
  symbol: string; // Benchmark symbol
  name: string; // Display name
  data: IndexPerformancePoint[]; // Performance data points
}

/**
 * Custom index calculation request
 */
export interface CustomIndexRequest {
  name: string; // Index name
  assets: IndexAsset[]; // Array of assets with weights
  timeframe: Timeframe; // Timeframe for calculation
  exchange: SupportedExchange; // Exchange to use
}

/**
 * Custom index response with performance data
 */
export interface CustomIndexResponse {
  name: string; // Index name
  exchange: string; // Exchange used
  timeframe: Timeframe; // Timeframe used
  assets: IndexAsset[]; // Assets in the index
  performance: IndexPerformancePoint[]; // Index performance data
  benchmarks: BenchmarkPerformance[]; // Comparison benchmarks
  startTime: number; // Start timestamp
  endTime: number; // End timestamp
  totalReturn: number; // Total percentage return
}

// ============================================================================
// Alt Screener Types
// ============================================================================

/**
 * Base currency for comparing altcoin performance
 * USD = absolute price, BTC/ETH/SOL = relative to that asset
 */
export type BaseCurrency = 'USD' | 'BTC' | 'ETH' | 'SOL';

/**
 * Time period for performance calculation
 */
export type PerformancePeriod = '1h' | '4h' | '24h' | '7d' | '30d';

/**
 * Sort options for the alt screener
 */
export type ScreenerSortBy = 'performance' | 'volume' | 'name' | 'price';

/**
 * Performance data for a single altcoin
 * Includes OHLCV data and calculated metrics
 */
export interface AltcoinPerformance {
  symbol: string; // Trading pair symbol (e.g., SOL-USDT)
  base: string; // Base currency (e.g., SOL)
  quote: string; // Quote currency (e.g., USDT)
  exchange: string; // Exchange identifier
  type: 'spot' | 'perp'; // Market type
  price: number; // Current price in USD
  priceInBase: number; // Current price in selected base currency
  change1h: number | null; // 1 hour percentage change
  change4h: number | null; // 4 hour percentage change
  change24h: number | null; // 24 hour percentage change
  change7d: number | null; // 7 day percentage change (if available)
  volume24h: number | null; // 24 hour volume in quote currency
  high24h: number | null; // 24 hour high price
  low24h: number | null; // 24 hour low price
  ohlcv: OHLCV[]; // Recent OHLCV data for mini chart
  rank?: number; // Rank by selected sort criteria
  timestamp: number; // Data timestamp
}

/**
 * Heatmap color intensity based on performance
 */
export interface HeatmapData {
  symbol: string;
  value: number; // Performance value for color calculation
  intensity: number; // Normalized intensity (0-1)
  color: 'green' | 'red' | 'neutral';
}

/**
 * Filter options for the alt screener
 */
export interface ScreenerFilters {
  minVolume?: number; // Minimum 24h volume in USD
  maxVolume?: number; // Maximum 24h volume in USD
  minChange?: number; // Minimum percentage change
  maxChange?: number; // Maximum percentage change
  type?: 'spot' | 'perp'; // Market type filter
  search?: string; // Symbol search query
}

/**
 * Request parameters for alt screener endpoint
 */
export interface AltScreenerRequest {
  exchange: SupportedExchange; // Exchange to fetch from
  baseCurrency: BaseCurrency; // Comparison base currency
  period: PerformancePeriod; // Performance calculation period
  sortBy: ScreenerSortBy; // Sort field
  sortOrder: 'asc' | 'desc'; // Sort direction
  limit?: number; // Maximum number of results
  filters?: ScreenerFilters; // Optional filters
}

/**
 * Base currency prices in USD for client-side calculations
 * Allows instant switching between comparison bases without API refetch
 */
export interface BaseCurrencyPrices {
  USD: 1; // Always 1 (USD is the reference)
  BTC: number; // BTC price in USD
  ETH: number; // ETH price in USD
  SOL: number; // SOL price in USD
}

/**
 * Response from alt screener endpoint
 */
export interface AltScreenerResponse {
  exchange: string; // Exchange identifier
  baseCurrency: BaseCurrency; // Comparison base used (initial/default)
  basePrice: number; // Current price of base currency in USD (for backwards compat)
  basePrices: BaseCurrencyPrices; // All base currency prices for client-side switching
  period: PerformancePeriod; // Performance period used
  altcoins: AltcoinPerformance[]; // Array of altcoin data (prices in USD)
  count: number; // Number of altcoins returned
  timestamp: number; // Response timestamp
  stats: {
    // Aggregate statistics
    totalAltcoins: number; // Total altcoins scanned
    gainers: number; // Count of gainers
    losers: number; // Count of losers
    avgChange: number; // Average percentage change
    topGainer: string; // Best performing symbol
    topLoser: string; // Worst performing symbol
  };
}
