/**
 * Shared types and interfaces between API and Web applications
 * This package provides type safety across the full stack
 */

/**
 * Standard API response wrapper for all endpoints
 */
export interface ApiResponse<T = any> {
  success: boolean;
  data: T;
  error: string | null;
  timestamp: number;
}

/**
 * Ticker data structure (cryptocurrency market data)
 *
 * Symbol Notation:
 * - Spot markets: BTC-USDT, SOL-USDT (hyphen separator)
 * - Perpetual markets: BTCUSDT.P, SOLUSDT.P (.P suffix)
 */
export interface Ticker {
  symbol: string; // Trading pair symbol (e.g., BTC-USDT for spot, BTCUSDT.P for perp)
  exchange: string; // Exchange identifier
  type: 'spot' | 'perp'; // Market type
  bid: number | null; // Highest bid price
  ask: number | null; // Lowest ask price
  last: number | null; // Last traded price
  high24h: number | null; // 24h highest price
  low24h: number | null; // 24h lowest price
  volume24h: number | null; // 24h base volume
  quoteVolume24h: number | null; // 24h quote volume
  change24h: number | null; // 24h absolute change
  percentage24h: number | null; // 24h percentage change
  timestamp: number; // Data timestamp
  fundingRate?: number | null; // Perpetual funding rate (perp only)
  openInterest?: number | null; // Perpetual open interest (perp only)
}

/**
 * Market information structure
 *
 * Symbol Notation:
 * - Spot markets: BTC-USDT, SOL-USDT (hyphen separator)
 * - Perpetual markets: BTCUSDT.P, SOLUSDT.P (.P suffix)
 */
export interface Market {
  id: string; // Market identifier
  symbol: string; // Trading pair symbol (e.g., BTC-USDT for spot, BTCUSDT.P for perp)
  base: string; // Base currency
  quote: string; // Quote currency
  type: 'spot' | 'perp'; // Market type
  active: boolean; // Is market active
  exchange: string; // Exchange identifier
}

/**
 * Exchange capabilities information
 */
export interface ExchangeInfo {
  name: string; // Display name
  id: string; // Exchange identifier
  supported: boolean; // Is supported
  hasSpot: boolean; // Has spot markets
  hasPerp: boolean; // Has perpetual markets
}

/**
 * Supported exchanges
 * - binance: Binance (spot + perpetual)
 * - bybit: Bybit (spot + perpetual)
 * - okx: OKX (spot + perpetual)
 * - hyperliquid: Hyperliquid DEX (perpetual only)
 * - upbit: Upbit Korea (spot only)
 */
export type SupportedExchange = 'binance' | 'bybit' | 'okx' | 'hyperliquid' | 'upbit';

/**
 * Pagination metadata
 */
export interface PaginationMeta {
  page: number; // Current page number (1-indexed)
  limit: number; // Items per page
  total: number; // Total number of items
  totalPages: number; // Total number of pages
  hasNext: boolean; // Has next page
  hasPrev: boolean; // Has previous page
}

/**
 * Tickers response from /tickers/:exchange
 */
export interface TickersResponse {
  exchange: string;
  tickers: Ticker[];
  count: number;
  pagination?: PaginationMeta; // Optional pagination metadata
  filters?: {
    // Applied filters
    type?: 'spot' | 'perp';
    search?: string;
    sortBy?: string;
    sortOrder?: 'asc' | 'desc';
  };
}

/**
 * Markets response from /markets/:exchange
 */
export interface MarketsResponse {
  exchange: string;
  markets: Market[];
  count: number;
  pagination?: PaginationMeta; // Optional pagination metadata
  filters?: {
    // Applied filters
    type?: 'spot' | 'perp';
    search?: string;
    active?: boolean;
  };
}

/**
 * Health check response
 */
export interface HealthResponse {
  status: string;
  api: string;
  database: string;
  exchanges: string[];
  timestamp: number;
}

/**
 * OHLCV candlestick data (Open, High, Low, Close, Volume)
 * Standard format for chart data across all timeframes
 */
export interface OHLCV {
  timestamp: number; // Candle start timestamp in milliseconds
  open: number; // Opening price
  high: number; // Highest price in the period
  low: number; // Lowest price in the period
  close: number; // Closing price
  volume: number; // Trading volume in base currency
}

/**
 * Supported timeframes for OHLCV data
 * Maps to standard exchange timeframe formats
 */
export type Timeframe = '1m' | '5m' | '15m' | '1h' | '4h' | '1d' | '3d' | '1w';

/**
 * OHLCV response from /ohlcv/:exchange/:symbol
 *
 * Symbol uses standardized notation:
 * - Spot: BTC-USDT
 * - Perpetual: BTCUSDT.P
 */
export interface OHLCVResponse {
  exchange: string; // Exchange identifier
  symbol: string; // Trading pair symbol (BTC-USDT or BTCUSDT.P)
  timeframe: Timeframe; // Requested timeframe
  candles: OHLCV[]; // Array of candlestick data
  count: number; // Number of candles returned
}

/**
 * Custom pair response from /custom-pair/:exchange/:symbol1/:symbol2
 * Generated by dividing two ticker prices (symbol1 / symbol2)
 */
export interface CustomPairResponse {
  exchange: string; // Exchange identifier
  symbol1: string; // Numerator symbol (e.g., BTC-USDT)
  symbol2: string; // Denominator symbol (e.g., AVAX-USDT)
  customPairSymbol: string; // Resulting pair (e.g., BTC/AVAX)
  timeframe: Timeframe; // Requested timeframe
  marketType: 'spot' | 'perp'; // Market type
  candles: OHLCV[]; // Array of custom pair candlestick data
  count: number; // Number of candles returned
}

/**
 * Asset weight configuration for custom index
 * Each asset has a symbol and its weight in the index (as percentage)
 */
export interface IndexAsset {
  symbol: string; // Asset symbol (e.g., BTC-USDT)
  weight: number; // Weight percentage (0-100)
}

/**
 * Custom index performance data point
 * Shows the index value at a specific timestamp
 */
export interface IndexPerformancePoint {
  timestamp: number; // Timestamp in milliseconds
  value: number; // Normalized index value (starts at 100)
  change: number; // Percentage change from start
}

/**
 * Comparison benchmark data
 * Performance data for USDT/BTC/ETH/SOL benchmarks
 */
export interface BenchmarkPerformance {
  symbol: string; // Benchmark symbol
  name: string; // Display name
  data: IndexPerformancePoint[]; // Performance data points
}

/**
 * Custom index calculation request
 */
export interface CustomIndexRequest {
  name: string; // Index name
  assets: IndexAsset[]; // Array of assets with weights
  timeframe: Timeframe; // Timeframe for calculation
  exchange: SupportedExchange; // Exchange to use
}

/**
 * Custom index response with performance data
 */
export interface CustomIndexResponse {
  name: string; // Index name
  exchange: string; // Exchange used
  timeframe: Timeframe; // Timeframe used
  assets: IndexAsset[]; // Assets in the index
  performance: IndexPerformancePoint[]; // Index performance data
  benchmarks: BenchmarkPerformance[]; // Comparison benchmarks
  startTime: number; // Start timestamp
  endTime: number; // End timestamp
  totalReturn: number; // Total percentage return
}

// ============================================================================
// Alt Screener Types
// ============================================================================

/**
 * Base currency for comparing altcoin performance
 * USD = absolute price, BTC/ETH/SOL = relative to that asset
 */
export type BaseCurrency = 'USD' | 'BTC' | 'ETH' | 'SOL';

/**
 * Time period for performance calculation
 */
export type PerformancePeriod = '1h' | '4h' | '24h' | '7d' | '30d';

/**
 * Sort options for the alt screener
 */
export type ScreenerSortBy = 'performance' | 'volume' | 'name' | 'price';

/**
 * Performance data for a single altcoin
 * Includes OHLCV data and calculated metrics
 */
export interface AltcoinPerformance {
  symbol: string; // Trading pair symbol (e.g., SOL-USDT)
  base: string; // Base currency (e.g., SOL)
  quote: string; // Quote currency (e.g., USDT)
  exchange: string; // Exchange identifier
  type: 'spot' | 'perp'; // Market type
  price: number; // Current price in USD
  priceInBase: number; // Current price in selected base currency
  change1h: number | null; // 1 hour percentage change
  change4h: number | null; // 4 hour percentage change
  change24h: number | null; // 24 hour percentage change
  change7d: number | null; // 7 day percentage change (if available)
  volume24h: number | null; // 24 hour volume in quote currency
  high24h: number | null; // 24 hour high price
  low24h: number | null; // 24 hour low price
  ohlcv: OHLCV[]; // Recent OHLCV data for mini chart
  rank?: number; // Rank by selected sort criteria
  timestamp: number; // Data timestamp
}

/**
 * Heatmap color intensity based on performance
 */
export interface HeatmapData {
  symbol: string;
  value: number; // Performance value for color calculation
  intensity: number; // Normalized intensity (0-1)
  color: 'green' | 'red' | 'neutral';
}

/**
 * Filter options for the alt screener
 */
export interface ScreenerFilters {
  minVolume?: number; // Minimum 24h volume in USD
  maxVolume?: number; // Maximum 24h volume in USD
  minChange?: number; // Minimum percentage change
  maxChange?: number; // Maximum percentage change
  type?: 'spot' | 'perp'; // Market type filter
  search?: string; // Symbol search query
}

/**
 * Request parameters for alt screener endpoint
 */
export interface AltScreenerRequest {
  exchange: SupportedExchange; // Exchange to fetch from
  baseCurrency: BaseCurrency; // Comparison base currency
  period: PerformancePeriod; // Performance calculation period
  sortBy: ScreenerSortBy; // Sort field
  sortOrder: 'asc' | 'desc'; // Sort direction
  limit?: number; // Maximum number of results
  filters?: ScreenerFilters; // Optional filters
}

/**
 * Base currency prices in USD for client-side calculations
 * Allows instant switching between comparison bases without API refetch
 */
export interface BaseCurrencyPrices {
  USD: 1; // Always 1 (USD is the reference)
  BTC: number; // BTC price in USD
  ETH: number; // ETH price in USD
  SOL: number; // SOL price in USD
}

/**
 * Response from alt screener endpoint
 */
export interface AltScreenerResponse {
  exchange: string; // Exchange identifier
  baseCurrency: BaseCurrency; // Comparison base used (initial/default)
  basePrice: number; // Current price of base currency in USD (for backwards compat)
  basePrices: BaseCurrencyPrices; // All base currency prices for client-side switching
  period: PerformancePeriod; // Performance period used
  altcoins: AltcoinPerformance[]; // Array of altcoin data (prices in USD)
  count: number; // Number of altcoins returned
  timestamp: number; // Response timestamp
  stats: {
    // Aggregate statistics
    totalAltcoins: number; // Total altcoins scanned
    gainers: number; // Count of gainers
    losers: number; // Count of losers
    avgChange: number; // Average percentage change
    topGainer: string; // Best performing symbol
    topLoser: string; // Worst performing symbol
  };
}

// ============================================================================
// Technical Indicator Types
// ============================================================================

/**
 * Configuration for which technical indicators to calculate
 */
export interface IndicatorConfig {
  sma?: number[]; // Array of SMA periods to calculate (e.g., [20, 50, 200])
  ema?: number[]; // Array of EMA periods to calculate (e.g., [12, 26])
  rsi?: number[]; // Array of RSI periods to calculate (e.g., [14])
}

/**
 * Single data point with OHLCV and calculated indicator values
 *
 * Each indicator type maps period numbers to their calculated values.
 * Null values indicate insufficient data to calculate the indicator at that point.
 */
export interface IndicatorDataPoint {
  timestamp: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  sma: Record<number, number | null>; // period -> SMA value
  ema: Record<number, number | null>; // period -> EMA value
  rsi: Record<number, number | null>; // period -> RSI value
}

/**
 * Response structure for technical indicators endpoint
 *
 * Contains the requested indicators configuration and all calculated values
 * aligned with the OHLCV timestamps.
 */
export interface TechnicalIndicatorResponse {
  exchange: string;
  symbol: string;
  timeframe: Timeframe;
  marketType: 'spot' | 'perp';
  indicators: {
    sma: number[]; // SMA periods that were calculated
    ema: number[]; // EMA periods that were calculated
    rsi: number[]; // RSI periods that were calculated
  };
  data: IndicatorDataPoint[];
  candleCount: number;
}

/**
 * Default technical indicator periods commonly used in trading
 *
 * SMA Periods:
 * - 20: Short-term trend (about 1 month for daily candles)
 * - 50: Medium-term trend (about 2.5 months for daily candles)
 * - 200: Long-term trend (about 10 months for daily candles)
 *
 * EMA Periods:
 * - 9/12/21/26: Common MACD and short-term trading periods
 *
 * RSI Period:
 * - 14: Standard RSI period developed by J. Welles Wilder
 */
export const DEFAULT_INDICATOR_PERIODS = {
  sma: [20, 50, 200],
  ema: [9, 12, 21, 26],
  rsi: [14],
} as const;

/**
 * Indicator line configuration for chart overlays
 */
export interface IndicatorLine {
  type: 'sma' | 'ema';
  period: number;
  color: string;
  width?: number;
  visible: boolean;
}

/**
 * RSI panel configuration
 */
export interface RSIConfig {
  period: number;
  overbought: number; // Typically 70
  oversold: number; // Typically 30
  visible: boolean;
}

// ============================================================================
// Funding Rate Analytics Types
// ============================================================================

/**
 * Funding rate data for a single perpetual contract
 *
 * Funding rate is a periodic payment between long and short traders in perpetual futures.
 * - Positive rate: Longs pay shorts (bullish sentiment, more longs)
 * - Negative rate: Shorts pay longs (bearish sentiment, more shorts)
 *
 * Traders use funding rates for:
 * 1. Arbitrage: Earn passive income by going long spot + short perp when funding is positive
 * 2. Sentiment analysis: Extreme funding often precedes market reversals
 * 3. Cross-exchange arbitrage: Compare funding across exchanges
 */
export interface FundingRateData {
  symbol: string; // Trading pair symbol (e.g., BTCUSDT.P)
  baseAsset: string; // Base currency (e.g., BTC)
  exchange: string; // Exchange identifier
  fundingRate: number; // Current funding rate (e.g., 0.0001 = 0.01%)
  fundingRatePercent: number; // Funding rate as percentage (e.g., 0.01)
  annualizedRate: number; // Annualized rate assuming 3x daily (e.g., 10.95 for 0.01% * 3 * 365)
  nextFundingTime: number | null; // Timestamp of next funding settlement
  markPrice: number | null; // Current mark price
  indexPrice: number | null; // Current index (spot) price
  openInterest: number | null; // Open interest in USD
  volume24h: number | null; // 24h trading volume in USD
  timestamp: number; // Data timestamp
}

/**
 * Cross-exchange funding rate comparison for a single asset
 * Useful for identifying arbitrage opportunities
 */
export interface CrossExchangeFunding {
  baseAsset: string; // Base currency (e.g., BTC)
  rates: {
    exchange: string; // Exchange identifier
    symbol: string; // Symbol on that exchange
    fundingRate: number; // Current funding rate
    fundingRatePercent: number; // Funding rate as percentage
    annualizedRate: number; // Annualized rate
    markPrice: number | null; // Mark price on this exchange
  }[];
  spread: number; // Max - Min funding rate spread
  maxExchange: string; // Exchange with highest funding
  minExchange: string; // Exchange with lowest funding
  arbitrageOpportunity: boolean; // True if spread is significant (>0.02%)
}

/**
 * Funding rate sentiment indicator
 */
export type FundingSentiment =
  | 'extremely_bullish'
  | 'bullish'
  | 'neutral'
  | 'bearish'
  | 'extremely_bearish';

/**
 * Market funding statistics
 */
export interface FundingMarketStats {
  totalPairs: number; // Total perpetual pairs analyzed
  positiveCount: number; // Pairs with positive funding
  negativeCount: number; // Pairs with negative funding
  neutralCount: number; // Pairs with near-zero funding
  avgFundingRate: number; // Average funding rate across all pairs
  avgFundingPercent: number; // Average funding as percentage
  marketSentiment: FundingSentiment; // Overall market sentiment
  highestFunding: {
    symbol: string;
    rate: number;
    percent: number;
  };
  lowestFunding: {
    symbol: string;
    rate: number;
    percent: number;
  };
}

/**
 * Funding rate analytics response
 */
export interface FundingRateResponse {
  exchange: string; // Exchange identifier
  fundingRates: FundingRateData[]; // Array of funding rate data
  count: number; // Number of pairs returned
  stats: FundingMarketStats; // Market statistics
  timestamp: number; // Response timestamp
}

/**
 * Cross-exchange funding rate comparison response
 */
export interface CrossExchangeFundingResponse {
  comparisons: CrossExchangeFunding[]; // Cross-exchange comparisons
  count: number; // Number of assets compared
  exchanges: string[]; // Exchanges included in comparison
  timestamp: number; // Response timestamp
  arbitrageOpportunities: {
    // Top arbitrage opportunities
    asset: string;
    spread: number;
    longExchange: string; // Exchange to go long (low funding)
    shortExchange: string; // Exchange to go short (high funding)
    estimatedDailyYield: number; // Estimated daily yield from funding arbitrage
  }[];
}

// ============================================================================
// Order Book Types
// ============================================================================

/**
 * Single order in the order book
 * Represents a price level with quantity
 */
export interface OrderBookEntry {
  price: number; // Price level
  amount: number; // Quantity at this price
  total: number; // Cumulative total up to this level
}

/**
 * Order book data structure
 * Contains bid (buy) and ask (sell) orders sorted by price
 *
 * Bids are sorted from highest to lowest (best bid first)
 * Asks are sorted from lowest to highest (best ask first)
 */
export interface OrderBook {
  symbol: string; // Trading pair symbol (e.g., BTC-USDT or BTCUSDT.P)
  exchange: string; // Exchange identifier
  type: 'spot' | 'perp'; // Market type
  bids: OrderBookEntry[]; // Buy orders (highest price first)
  asks: OrderBookEntry[]; // Sell orders (lowest price first)
  timestamp: number; // Data timestamp
  nonce?: number; // Exchange-specific sequence number (if available)
}

/**
 * Order book response from /orderbook/:exchange/:symbol
 */
export interface OrderBookResponse {
  exchange: string; // Exchange identifier
  symbol: string; // Trading pair symbol
  type: 'spot' | 'perp'; // Market type
  orderbook: OrderBook; // Order book data
  depth: number; // Number of price levels returned
  spread: number | null; // Bid-ask spread in price units
  spreadPercent: number | null; // Bid-ask spread as percentage
  midPrice: number | null; // Mid-market price
  timestamp: number; // Response timestamp
}

// ============================================================================
// Liquidation Monitor Types
// ============================================================================

export * from './liquidation';
