import { parse } from 'yaml';

const yamlPath = new URL('../apps/api/src/api-spec.yaml', import.meta.url);
const outputPath = new URL('../apps/api/src/generated-openapi.ts', import.meta.url);
const source = await Bun.file(yamlPath).text();
const document = parse(source) as Record<string, unknown>;
const generated = `// Generated by scripts/generate-openapi-module.ts. Do not edit by hand.\nexport const OPENAPI_DOCUMENT = ${JSON.stringify(document, null, 2)} as const;\n`;
await Bun.write(outputPath, generated);
