import { parse } from 'yaml';
import { format, resolveConfig } from 'prettier';

const yamlPath = new URL('../apps/api/src/api-spec.yaml', import.meta.url);
const outputPath = new URL('../apps/api/src/generated-openapi.ts', import.meta.url);
const source = await Bun.file(yamlPath).text();
const document = parse(source) as Record<string, unknown>;
const generated = `// Generated by scripts/generate-openapi-module.ts. Do not edit by hand.\nexport const OPENAPI_DOCUMENT = ${JSON.stringify(document, null, 2)} as const;\n`;
const prettierConfig = (await resolveConfig(outputPath.pathname)) ?? {};
await Bun.write(
  outputPath,
  await format(generated, { ...prettierConfig, filepath: outputPath.pathname })
);
